QuantityInput: clear input onFocus
jeremyckahn/farmhand pull request #121
Opened 2021-06-17 19:42 UTC by seawolff

#### What does this PR do?
Sorry this is somewhat of an opinionated change. But I found it annoying that I couldn't clear the default value of the controlled component completely when writing out a desired amount. i.e. if the value amount was `1` and I wanted `50` I'd have to start typing my desired amount and clear the value. So I am proposing we just clear the quantity input value on focus.

![Screenflick Movie 135](https://user-images.githubusercontent.com/147572/122461462-0235ba00-cf79-11eb-9e72-967c3fdbc3d3.gif)
![Screenflick Movie 134](https://user-images.githubusercontent.com/147572/122461473-0530aa80-cf79-11eb-868f-3eb330b75651.gif)

#### How can this change be manually tested?
Select the Quantity Input for both buying and selling an item and notice that when you select the input the previous default value clears. The Buy/Sell button should be disabled if an undefined value is current set.

#### Questions or concerns about this change?
I could perhaps make the disabled item button check a bit cleaner but for now I just added to the conditional to check if the purchase or sell quantity isn't defined.

2021-06-18 01:41 UTC, jeremyckahn commented
It looks like this PR fixes #98, yeah @lstebner?

2021-06-18 02:06 UTC, jeremyckahn requested changes
This is a really strong start to a much-appreciated change! I left a few notes for some minor things to revisit. There's one thing missing, and that's the same treatment being given to Recipe cards. It's worth adding that before shipping this to keep the UX consistent throughout the game.

You should be able to apply similar logic to [`Recipe.js`](https://github.com/jeremyckahn/farmhand/blob/wolff/quanity-input-onfocus-clear/src/components/Recipe/Recipe.js). I think you'll want to look here: https://github.com/jeremyckahn/farmhand/blob/2b86fba4fba8d9a0b4cbb8d76f6a64e57aa51bd9/src/components/Recipe/Recipe.js#L80-L90

And here: https://github.com/jeremyckahn/farmhand/blob/2b86fba4fba8d9a0b4cbb8d76f6a64e57aa51bd9/src/components/Recipe/Recipe.js#L133-L141

2021-06-18 15:23 UTC, lstebner commented
i'm noticing a small bug where after the input is cleared now it is impossible to use the up/down arrows to adjust the quantity. i wouldn't actually expect the input to clear on focus as a user, but instead after i hit 'delete' it should be ok with the input staying empty rather than trying to force a value to always be there.

2021-06-18 18:09 UTC, seawolff commented
@lstebner yeah perhaps this brings up a good point. Perhaps we should just remove the min-max validation check and allow for a non-controlled component so the input can be cleared out.

2021-06-18 18:25 UTC, seawolff commented
...actually, what if I just disabled the arrows as well?

2021-06-18 19:18 UTC, lstebner commented
that would make this a lot less user friendly in my opinion when the goal is to make it more intuitive. i still think the clearing on focus is already unexpected. 



> On Jun 18, 2021, at 11:25 AM, Wolff ***@***.***> wrote:
> 
> ﻿
> ...actually, what if I just disabled the arrows as well?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-18 21:16 UTC, seawolff commented
@jeremyckahn okay I think 🤞 this should be GTG

2021-06-19 00:19 UTC, jeremyckahn commented
> @jeremyckahn okay I think 🤞 this should be GTG

We’re getting there! I noticed that the arrow buttons don’t work at all for recipes. I’m mobile now but I can take a look at the code this weekend sometime to see what the issue may be!

2021-06-19 00:24 UTC, jeremyckahn commented
As for general UX around these components, I expect that it will be hard to get them perfect. We need some level of input constraint. There’s a lot of ways to solve that problem, ranging from simply showing an error UI to preventing invalid input (which is what we currently have). I’m open to solving this problem in a more effective or simple way. I don’t think we need to aim for perfection with this PR (or any other one for that matter), but each PR should at least be a net positive for the user and not be introducing greater problems for us to deal with later.

I think the basic idea of clearing the input upon focus is a step in the right direction and one I’d be happy to ship. I think there’s more work to be done here, but we can iterate with more PRs until we get it right!

2021-06-19 00:39 UTC, seawolff commented
> > @jeremyckahn okay I think 🤞 this should be GTG
> 
> 
> 
> We’re getting there! I noticed that the arrow buttons don’t work at all for recipes. I’m mobile now but I can take a look at the code this weekend sometime to see what the issue may be!

Ah sorry. I'll take a closer look Monday. I had a quick second and tried to fix. I'll take a more thorough approach Monday. Thanks for the feedback.

2021-06-19 16:27 UTC, seawolff commented
Ah I found the issue. I forgot to actually add `Math.max` and so it was just using 1 and was never incrementing the value. cc @jeremyckahn 

Sorry I normally never code on my day off, this is what you get 😜

2021-06-19 17:44 UTC, jeremyckahn approved these changes
This looks great to me! I think this change will make the Item/Recipe inputs much easier to work with, especially on mobile. We should keep iterating here, but this is a net positive. LGTM!

@seawolff please **squash merge** this PR and ship it. I'll walk you through how to run a release on Discord!

2021-06-19 17:45 UTC, merged