added consant for inventory limit
jeremyckahn/farmhand pull request #292
Opened 2022-06-12 21:37 UTC by kvaithin

### What this PR does
Close #291 

Updated to use constant for inventory limit value.

### How this change can be validated
No functionality change. Refactor to reuse constant inventory limit value.

2022-06-12 22:02 UTC, jeremyckahn requested changes
Hi @kvaithin, thanks for picking up #291 and opening this PR! I really appreciate the help. 

The code here generally looks good, but I think this is going to need to wait until #289 is merged. These PRs are touching a lot of the same code, and it'll be less risky to get that in and then either rebase your branch on top of `develop` or `git merge` it in.

Finishing #289 is my top priority, so hopefully you won't have to wait too long. Sorry for the inconvenience. I didn't think anyone would pick up #291 so quickly! 😅

2022-06-12 23:36 UTC, kvaithin commented
> Hi @kvaithin, thanks for picking up #291 and opening this PR! I really appreciate the help.
> 
> The code here generally looks good, but I think this is going to need to wait until #289 is merged. These PRs are touching a lot of the same code, and it'll be less risky to get that in and then either rebase your branch on top of `develop` or `git merge` it in.
> 
> Finishing #289 is my top priority, so hopefully you won't have to wait too long. Sorry for the inconvenience. I didn't think anyone would pick up #291 so quickly! 😅

Sure, will keep a lookout for #289 completion. 👍

2022-06-12 23:36 UTC, kvaithin commented on src/constants.js
> +export const INVENTORY_LIMIT = -1
Sounds good. Updated to `INFINITE_STORAGE_LIMIT`.

2022-06-13 00:01 UTC, jeremyckahn commented
https://github.com/jeremyckahn/farmhand/pull/289 has just been merged! Sorry for the conflicts you'll have to deal with @kvaithin. In case it's easier just to start fresh, feel free to close this PR and open a new one. Let me know if I can help you at all!

2022-06-13 00:41 UTC, kvaithin commented
> #289 has just been merged! Sorry for the conflicts you'll have to deal with @kvaithin. In case it's easier just to start fresh, feel free to close this PR and open a new one. Let me know if I can help you at all!

Np, closing this PR. Raised #293

2022-06-13 00:41 UTC, closed without merging